// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWrongQuestion(arg1, arg2) {
  return window['go']['main']['App']['AddWrongQuestion'](arg1, arg2);
}

export function AddWrongQuestionsFromSession(arg1) {
  return window['go']['main']['App']['AddWrongQuestionsFromSession'](arg1);
}

export function ClearDemoData() {
  return window['go']['main']['App']['ClearDemoData']();
}

export function CreatePracticeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePracticeSession'](arg1, arg2, arg3);
}

export function CreateQuestion(arg1) {
  return window['go']['main']['App']['CreateQuestion'](arg1);
}

export function CreateQuestionGroup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateQuestionGroup'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteQuestion(arg1) {
  return window['go']['main']['App']['DeleteQuestion'](arg1);
}

export function DeleteQuestionGroup(arg1) {
  return window['go']['main']['App']['DeleteQuestionGroup'](arg1);
}

export function ExportGroupAsCSV(arg1) {
  return window['go']['main']['App']['ExportGroupAsCSV'](arg1);
}

export function ExportSelectiveData(arg1) {
  return window['go']['main']['App']['ExportSelectiveData'](arg1);
}

export function ExportUserData() {
  return window['go']['main']['App']['ExportUserData']();
}

export function GetPracticeSessions() {
  return window['go']['main']['App']['GetPracticeSessions']();
}

export function GetQuestionByID(arg1) {
  return window['go']['main']['App']['GetQuestionByID'](arg1);
}

export function GetQuestionGroups() {
  return window['go']['main']['App']['GetQuestionGroups']();
}

export function GetQuestions() {
  return window['go']['main']['App']['GetQuestions']();
}

export function GetQuestionsByGroup(arg1) {
  return window['go']['main']['App']['GetQuestionsByGroup'](arg1);
}

export function GetUserSetting(arg1) {
  return window['go']['main']['App']['GetUserSetting'](arg1);
}

export function GetUserSettings() {
  return window['go']['main']['App']['GetUserSettings']();
}

export function GetWeakestTopics() {
  return window['go']['main']['App']['GetWeakestTopics']();
}

export function GetWrongQuestions() {
  return window['go']['main']['App']['GetWrongQuestions']();
}

export function GetWrongQuestionsForPractice() {
  return window['go']['main']['App']['GetWrongQuestionsForPractice']();
}

export function GetWrongQuestionsWithDetails() {
  return window['go']['main']['App']['GetWrongQuestionsWithDetails']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportQuestions(arg1, arg2) {
  return window['go']['main']['App']['ImportQuestions'](arg1, arg2);
}

export function ImportQuestionsFromCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportQuestionsFromCSV'](arg1, arg2);
}

export function ImportUserData(arg1) {
  return window['go']['main']['App']['ImportUserData'](arg1);
}

export function InitializeDemoData() {
  return window['go']['main']['App']['InitializeDemoData']();
}

export function IsQuestionMarkedWrong(arg1) {
  return window['go']['main']['App']['IsQuestionMarkedWrong'](arg1);
}

export function RemoveWrongQuestion(arg1) {
  return window['go']['main']['App']['RemoveWrongQuestion'](arg1);
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function SaveFileToDownloads(arg1, arg2) {
  return window['go']['main']['App']['SaveFileToDownloads'](arg1, arg2);
}

export function SavePracticeSession(arg1) {
  return window['go']['main']['App']['SavePracticeSession'](arg1);
}

export function SetUserSetting(arg1, arg2) {
  return window['go']['main']['App']['SetUserSetting'](arg1, arg2);
}

export function ToggleWrongQuestion(arg1, arg2) {
  return window['go']['main']['App']['ToggleWrongQuestion'](arg1, arg2);
}

export function UpdateQuestion(arg1) {
  return window['go']['main']['App']['UpdateQuestion'](arg1);
}

export function UpdateQuestionGroup(arg1) {
  return window['go']['main']['App']['UpdateQuestionGroup'](arg1);
}

export function UpdateUserSettings(arg1) {
  return window['go']['main']['App']['UpdateUserSettings'](arg1);
}

export function UpdateWrongQuestionReview(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWrongQuestionReview'](arg1, arg2, arg3);
}
